### PR TITLE
fix, tidy: cmake project was failing to configure.

### PR DESCRIPTION
**Pull request by biojppm**
the main point is fixing a problem in `add_test()` where NAME was not available (it cannot be both an explicit macro argument and an entry to `cmake_parse_arguments()`)

Also, refactored some boilerplate cmake code to functions, and organized the project into folders:

image

### CODE REVIEW

**Comment by jk-jeon** [comment]
Thanks for the PR. I like all of changes you made. But could you explain what `buffer.h` is?

**Comment by biojppm** [comment]
> could you explain what buffer.h is?

Oh, sorry - that was not meant to go in yet; it will be the subject of a future PR - but not yet. I will amend the commit.

**Comment by biojppm** [comment]
Done.

**Comment by jk-jeon** [comment]
Thanks again!

**Pull request merged**
